version: "2"
services:
  node:
    image: node:8
    container_name: pizza
    volumes:
    - ./app:/app
    ports:
    - "8081:8081"
    environment:
    - NODE_ENV = DEV
    - PORT = 8081
    working_dir: /app
    command: bash -c "npm install && npm start"
    restart: always
